# Generated by Django 5.1.5 on 2025-03-25 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('date_of_birth', models.DateField()),
                ('course', models.CharField(choices=[('CS', 'Computer Science'), ('ENG', 'Engineering'), ('BUS', 'Business'), ('ART', 'Arts'), ('SCI', 'Science')], max_length=3)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
